/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: {
          DEFAULT: 'var(--surface)',
          0: 'var(--surface-0)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          hover: 'var(--surface-hover)',
          elevated: 'var(--surface-elevated)',
        },
        border: 'var(--border)',
        'border-hover': 'var(--border-hover)',
        'border-strong': 'var(--border-strong)',
        'border-gold': 'var(--border-gold)',
        gold: {
          DEFAULT: 'var(--gold)',
          soft: 'var(--gold-soft)',
          text: 'var(--gold-text)',
          dim: 'var(--gold-dim)',
          border: 'var(--border-gold)',
        },
        accent: {
          blue: 'var(--blue)',
          'blue-dim': 'var(--blue-dim)',
          green: 'var(--green)',
          'green-dim': 'var(--green-dim)',
          red: 'var(--red)',
          'red-dim': 'var(--red-dim)',
          amber: 'var(--amber)',
          'amber-dim': 'var(--amber-dim)',
          purple: 'var(--purple)',
          'purple-dim': 'var(--purple-dim)',
          orange: 'var(--orange)',
          'orange-dim': 'var(--orange-dim)',
          gold: 'var(--gold)',
          'gold-dim': 'var(--gold-dim)',
        },
        ink: {
          900: 'var(--ink-900)',
          800: 'var(--ink-800)',
          700: 'var(--ink-700)',
          600: 'var(--ink-600)',
          500: 'var(--ink-500)',
          400: 'var(--ink-400)',
          300: 'var(--ink-300)',
        },
        text: {
          DEFAULT: 'var(--text)',
          sec: 'var(--text-sec)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          dim: 'var(--muted-dim)',
        },
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'monospace'],
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['DM Serif Display', 'Georgia', 'serif'],
      },
      boxShadow: {
        'glow-gold': '0 0 24px rgba(204, 160, 0, 0.18)',
        'glow-gold-strong': '0 0 60px rgba(224, 184, 46, 0.30)',
        'card': '0 4px 16px rgba(15, 23, 42, 0.06), 0 1px 2px rgba(15, 23, 42, 0.04)',
        'card-lg': '0 24px 60px rgba(4, 58, 118, 0.18), 0 4px 12px rgba(15, 23, 42, 0.06)',
      },
      transitionTimingFunction: {
        'out-soft': 'cubic-bezier(0.22, 1, 0.36, 1)',
        spring: 'cubic-bezier(0.34, 1.2, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
